# Generated by Django 2.2 on 2019-04-15 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_about',
            field=models.TextField(default='Nothing here to show.'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_description',
            field=models.TextField(default='Nothing here to show.'),
        ),
    ]
