# Generated by Django 2.2 on 2019-04-23 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_restaurant_restaurant_queue'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_lat',
            field=models.FloatField(default=12.931641),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_long',
            field=models.FloatField(default=79.13624),
        ),
    ]
